spring:
  datasource:
    url:
      jdbc:mysql://db:3306/userdb?createDatabaseIfNotExist=true&autoReconnect=true
      &characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    password: password
  jpa:
    hibernate:
      ddl-auto: create